### PR TITLE
(3.8) Replace deprecated ast literals

### PR DESCRIPTION
**Pull request by FozzieHi**
Tracking issue: #365

See python/cpython#77073:
> Num -- for int, float and complex
Str -- for str
Bytes -- for bytes
Ellipsis -- for Ellipsis
NameConstant -- for True, False and None

This looks a bit messy in places but I don't think a helper function would provide that much improved readability (it'd effectively just be re-implementing the deprecation's, which we don't want), and we only use this in a relatively small portion of the code base.

I've just replaced the deprecated literals with their actual meanings, I'm not too sure whether we now want to change some (for example ast.Num checks for int, float and complex but we might only want to check for int).

### CODE REVIEW

**Comment by FozzieHi** [comment]
Oh right, we might want to disable the 3.7 ci run first :facepalm:

**Comment by cooperlees** [comment]
> Oh right, we might want to disable the 3.7 CI run first facepalm

Maybe we should do this in a PR we land before this turning off CI, adjusting pyproject.toml and anything else that ups our minimums for tools ...

**Comment by FozzieHi** [comment]
@cooperlees Just read my mind, submitting a PR for that now.

**Comment by cooperlees** [comment]
> @cooperlees Just read my mind, submitting a PR for that now.

I'm around for a few hours so can merge quickly to make rebasing this easier.

**Review by cooperlees — APPROVED** [review]
All tests pass and we have good coverage so pretty confident here.

**Pull request merged**
