### PR TITLE
B018: Find more constants w/o assign

### PR DESCRIPTION
**Pull request by kasium**
This check now also finds:
* numbers (ints, float, complex)
* lists
* sets
* dicts
* binary strings
* joined strings (f-strings)
* name constants (True, False, None)

This is part 1 of #200 . The second part will enable the check for modules

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
SGTM - This makes b018 much more complete.  Thanks for the efforts. /me wonders how many weird typos across the world this will pickup.

I'll look to release over the weekend / Monday (west coast USA) time ...

**Comment by asottile** [comment]
I think this still misses a few things, such as this subtle bug:

```python
def f():
    f"string"
```

**Comment by kasium** [comment]
@asottile thanks for your feedback. If I'm not wrong, JoinedStr is catched:
https://github.com/PyCQA/flake8-bugbear/blob/master/bugbear.py#L589

And a f-string w/o parameter is catched in pyflakes I guess

**Comment by asottile** [comment]
it's only caught at body positions 1+

**Comment by kasium** [comment]
Ah, yes. You are right.

However, I'm not sure if this should be covered here. It's not recommended to use `"` as the docstring and to find out which quotes where used, I guess tokens are needed. Therefore, I see this more in https://pypi.org/project/flake8-docstrings/.

@cooperlees what do you think?

**Comment by asottile** [comment]
no all I'm suggesting is to extend the check to 0+ instead of 1+ and add an exception for Str at 0

**Comment by kasium** [comment]
Sorry, that was clear 😄. Let me open a PR. That's a great idea!

**Pull request merged**
