### PR TITLE
Add b024: abstract class with no abstract methods

### PR DESCRIPTION
**Pull request by jakkdl**
First requested error in #273

### CODE REVIEW

**Comment by jakkdl** [comment]
Couple possibilities on how liberal the name checks should be to balance false/missed alarms. You can check `tests/b024.py` for where the line is drawn currently.

@Zac-HD

**Comment by Zac-HD** [comment]
I'd warn only if the name is exactly `ABC` or `abc.ABC`, missing the alarm if you `[from ...] import ... as` seems fine to me.

**Comment by jakkdl** [comment]
I was thinking more if any other libraries implement `ABC`'s, but I guess that's very rarely the case (and it that case they might be doing fancy stuff such that this would be a false alarm anyway).

(Previous CI run failed due to me forgetting to update lines after black formatted the test file)

**Comment by cooperlees** [comment]
Hmm - Where be the CI? I clicked approve :|

**Comment by Zac-HD** [comment]
Stuck in queued, and there's an incident https://www.githubstatus.com/incidents/8gpymn7rystj

Should be fine in a few hours?

**Review by Zac-HD — APPROVED** [review]
Looks great - thanks @jakkdl!

**Pull request merged**
